package com.ofsoft.cms.model;


import com.ofsoft.cms.model.base.BaseSysHomeModule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysHomeModule extends BaseSysHomeModule<SysHomeModule> {
	public static final SysHomeModule dao = new SysHomeModule().dao();
}
