package com.ofsoft.cms.model;


import com.ofsoft.cms.model.base.BaseSysHelpInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysHelpInfo extends BaseSysHelpInfo<SysHelpInfo> {
	public static final SysHelpInfo dao = new SysHelpInfo().dao();
}
