package com.ofsoft.cms.model;


import com.ofsoft.cms.model.base.BaseSysScrollPic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysScrollPic extends BaseSysScrollPic<SysScrollPic> {
	public static final SysScrollPic dao = new SysScrollPic().dao();
}
