package com.ofsoft.cms.model;


import com.ofsoft.cms.model.base.BaseSysSms;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysSms extends BaseSysSms<SysSms> {
	public static final SysSms dao = new SysSms().dao();
}
